services:

#### Container para Banco de Dados Transacional e Dimensional
  postgres_liga_sudoers:
    image: postgres:latest
    container_name: postgres_liga_sudoers
    environment:
      POSTGRES_USER: sudoers
      POSTGRES_PASSWORD: password
      POSTGRES_DB: liga_sudoers
    ports:
      - "5434:5432"
    volumes:
      - pgdata_liga_sudoers:/var/lib/postgresql/data
      - ./modelagem/ddl/liga_sudoers.sql:/docker-entrypoint-initdb.d/liga_sudoers.sql

  postgres_liga_sudoers_dw:
    image: postgres:latest
    container_name: postgres_liga_sudoers_dw
    environment:
      POSTGRES_USER: sudoers
      POSTGRES_PASSWORD: password
      POSTGRES_DB: liga_sudoers_dw
    ports:
      - "5433:5432"
    volumes:
      - pgdata_liga_sudoers_dw:/var/lib/postgresql/data_dw
      - ./modelagem/ddl/liga_sudoers_dw.sql:/docker-entrypoint-initdb.d/liga_sudoers_dw.sql

#### Container para ETL's 

  etl_scripts:
    image: apache/hop-web:latest
    container_name: etl_scripts
    depends_on:
      - postgres_liga_sudoers
      - postgres_liga_sudoers_dw
    ports:
      - "8080:8080"
    environment:      
     - HOP_PROJECT_FOLDER=/files
     - HOP_PROJECT_NAME=default
    volumes:
      - ./etl_sudoers:/files
    working_dir: /files

#### Container para Dashboards

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: metabase_db
    depends_on:
      - metabase_db

  metabase_db:
    image: postgres:13
    container_name: metabase_db
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_DB: metabase
    ports:
      - "5436:5432"
    volumes:
      - metabase_db_data:/var/lib/postgresql/data
      - ./dashboard/metabase_db/metabase_backup.sql:/docker-entrypoint-initdb.d/metabase_backup.sql

volumes:
  metabase_db_data:
  pgdata_liga_sudoers:
  pgdata_liga_sudoers_dw:
