services:

#### Container para Banco de Dados Transacional e Dimensional
  postgres_liga_sudoers:
    image: postgres:latest
    container_name: postgres_liga_sudoers_dm01
    environment:
      POSTGRES_USER: sudoers
      POSTGRES_PASSWORD: password
      POSTGRES_DB: liga_sudoers
    ports:
      - "5434:5432"
    volumes:
      - pgdata_liga_sudoers:/var/lib/postgresql/data
      - ./ddl/liga_sudoers.sql:/docker-entrypoint-initdb.d/liga_sudoers.sql

  postgres_liga_sudoers_dw:
    image: postgres:latest
    container_name: postgres_liga_sudoers_dw_dm01
    environment:
      POSTGRES_USER: sudoers
      POSTGRES_PASSWORD: password
      POSTGRES_DB: liga_sudoers_dw
    ports:
      - "5433:5432"
    volumes:
      - pgdata_liga_sudoers_dw:/var/lib/postgresql/data_dw
      - ./ddl/liga_sudoers_dw.sql:/docker-entrypoint-initdb.d/liga_sudoers_dw.sql

volumes:
  pgdata_liga_sudoers:
  pgdata_liga_sudoers_dw:
